server:
  port: 31000
  logging:
    level: warn
  limit: 512
redis:
  addrs:
    - redis-service:26379
  password: ZljIsysc0re123
  db: 7
loki:
  host: http://loki-service:3100
rc:
  host: http://isc-rc-application-service:34200
  relevance: "/api/rc-application/application/service/relevance"

mysql:
  host: mysql-service:23306
  user_name: isyscore
  password: Isysc0re
  data_base: isc_service