server:
  port: 31000
redis:
  addrs:
    - 10.30.30.78:26379
  password: ZljIsysc0re123
  db: 7
loki:
  host: http://10.30.30.87:3100
rc:
  host: http://10.30.30.78:34200
  relevance: "/api/rc-application/application/service/relevance"
