server:
  port: 31000
  limit: 512
  compatible: true
redis:
  addrs:
    - redis-service:26379
  password: ZljIsysc0re123
  db: 7
loki:
  host: http://loki-service:3100
rc:
  host: http://10.30.30.78:34200
  relevance: "/api/rc-application/application/service/relevance"

mysql:
  host: 10.30.30.78:23306
  user_name: isyscore
  password: Isysc0re
  data_base: isc_service