server:
  port: 31000
redis:
  master: master
  addrs:
    - 10.30.30.78:26379
  password: ZljIsyscore123
  db: 7
mysql:
  host: 10.30.30.78:23306
  user_name: root
  password: Isysc0re
  data_base: isc_service